.github/workflows/CI.yml
.github/workflows/test.yml
crates/uroborosql-fmt-cli/src/main.rs
crates/uroborosql-fmt-napi/src/lib.rs
crates/uroborosql-fmt-wasm/src/lib.rs
crates/uroborosql-fmt/src/cst.rs
crates/uroborosql-fmt/src/cst/body/with.rs
crates/uroborosql-fmt/src/cst/expr.rs
crates/uroborosql-fmt/src/cst/expr/aligned.rs
crates/uroborosql-fmt/src/cst/expr/function.rs
crates/uroborosql-fmt/src/lib.rs
crates/uroborosql-fmt/src/re.rs
crates/uroborosql-fmt/src/two_way_sql.rs
crates/uroborosql-fmt/src/validate.rs
crates/uroborosql-fmt/src/visitor/clause/with.rs
crates/uroborosql-fmt/src/visitor/expr/in_expr.rs
crates/uroborosql-fmt/tests/test_all.rs

close #13 
1. 以下のコマンドを実行するワークフロー(.github/workflows/test.yml)を追加しました:
* `cargo check`
* `cargo fmt`
* `cargo test`
* `cargo clippy`
2. ビルド前にテストを実行するように修正しました

Add workflow that tests and checks

---

wasm/index.html
wasm/main.js
wasm/style.css

- 全ての設定に対応
- 設定をローカルストレージに保持するように変更
- formatボタンを押した際にローカルストレージに保存される
- 起動時にローカルストレージから設定を読み込む
- defaultボタン、select_allボタン、clear_allボタンの実装
- オプションのテキストにホバーすると具体例が表示されるように変更
1. [gh-pagesブランチ](https://github.com/future-architect/uroborosql-fmt/tree/gh-pages)の`uroborosql-fmt.js`、`uroborosql-fmt.wasm`を`wasm/`以下にコピー
2. 適当な方法でローカルでサーバを立てて動作確認
close #21

Support for all settings and save settings to local storage

---

README.md
wasm/index.html
wasm/ja.html
wasm/style.css

wasm版デモの英語版に対応しました
- 既存の`wasm/index.html`(日本語で記述)を`wasm/ja.html`に変更
- 英語版の`wasm/index.html`を新たに作成
Close #23 
Close #26

English support for the demo by wasm

---

.github/workflows/CI.yml
Cargo.lock
build.sh
crates/uroborosql-fmt-wasm/Cargo.toml
crates/uroborosql-fmt-wasm/src/lib.rs
wasm/index.html
wasm/ja.html
wasm/main.js

wasm版demoにおいて、フォーマットに失敗した際にエラーメッセージを表示するように変更しました。 (#25 )
ただし、UroboroSQLFmtErrorを単純に文字列に変更して表示しているため、エラー内容はわかりにくいものとなっています。
エラーメッセージの内容については別で議論する必要があると思うので、とりあえずドラフトの形でPRを作成しました。
以前は`format_sql_for_wasm`でフォーマット結果を格納したポインタを返していました。
しかし、今回の変更ではフォーマット結果とエラーメッセージの2つの文字列を返したいため、実装を以下のように変更しました。
1. Rustであらかじめ結果とエラーメッセージを格納するメモリを確保 (それぞれ`RESULT`、`ERROR_MSG`とする。現状大きさ50000としている。)
2. wasmの初期化時に`RESULT`と`ERROR_MSG`の先頭アドレスを取得 (Rust側でアドレスを教える関数を作成して実現)
4. `format_sql_for_wasm`が呼び出されたらフォーマットを実行し、正常ならば結果を`RESULT`に、エラーの場合はエラーメッセージを`ERROR_MSG`に格納
5. js側で`RESULT`、`ERROR_MSG`から結果とエラーメッセージを取得して表示

Display error messages in the wasm demo

---

Cargo.lock
crates/uroborosql-fmt/src/visitor/statement/delete.rs
crates/uroborosql-fmt/testfiles/dst/delete/using.sql
crates/uroborosql-fmt/testfiles/src/delete/using.sql

`DELETE`における`using`に対応しました。
input
```sql
delete from tbl_a a
using tbl_b b, tbl_c c
where a.col1 = b.col1 and b.col2 > 10 and c.col3 = 'abc';
```
result
```sql
delete
from
tbl_a	a
using
tbl_b	b
,	tbl_c	c
where
a.col1	=	b.col1
and	b.col2	>	10
and	c.col3	=	'abc'
;
```

Support using clause in DELETE statement

---

.uroborosqlfmtrc.json
README.md
crates/uroborosql-fmt-cli/src/main.rs

VSCode拡張に合わせて設定ファイルの名前を`uroborosqlfmt-config.json`から`.uroborosqlfmtrc.json`に変更しました．
Close #40

Rename the configuration file to .uroborosqlfmtrc.json

---

crates/uroborosql-fmt/src/cst/expr.rs
crates/uroborosql-fmt/src/two_way_sql/merge.rs
crates/uroborosql-fmt/src/validate.rs
crates/uroborosql-fmt/src/visitor/clause.rs
crates/uroborosql-fmt/src/visitor/clause/group_by.rs
crates/uroborosql-fmt/src/visitor/clause/having.rs
crates/uroborosql-fmt/testfiles/dst/select/group_by.sql
crates/uroborosql-fmt/testfiles/src/select/group_by.sql

HAVING句がAND/ORを持つ場合にインデントがずれていたバグを修正しました。
After: 
```sql
select
id			as	id
,	sum(cnt)
from
tbl
group by
id
having
sum(cnt)	>	1
and	avg(cnt)	<	10
;
```
close #49

Correction indentation when the HAVING clause contains AND/OR

---

crates/uroborosql-fmt/src/cst/expr/unary.rs
crates/uroborosql-fmt/src/visitor/expr.rs
crates/uroborosql-fmt/src/visitor/expr/unary.rs
crates/uroborosql-fmt/testfiles/dst/select/unary.sql
crates/uroborosql-fmt/testfiles/src/select/unary.sql

close #53 
単項演算子をサポートする修正をおこないました
input:
```sql
select -10 as negative_value
```
output:
```sql
select
-10	as	negative_value
```

Support Unary operators

---

crates/uroborosql-fmt/src/visitor/clause/with.rs
crates/uroborosql-fmt/testfiles/dst/select/with.sql
crates/uroborosql-fmt/testfiles/src/select/with.sql

fix #61
with句の中の閉じ括弧直前に複数コメントがある場合にもエラーにならずフォーマットされるようにしました
```sql
with T as (
select
*
from
T	t
where
1		=	1
AND	t.id	=	1	-- ID
-- multiple
-- formatted
-- comments
)
select
*
from T t
```

Fix consecutive comments at the end of with_clause parentheses

---

crates/uroborosql-fmt/src/cst.rs
crates/uroborosql-fmt/src/cst/body/separeted_lines.rs
crates/uroborosql-fmt/src/visitor/clause/order_by.rs
crates/uroborosql-fmt/testfiles/dst/2way_sql/comment.sql
crates/uroborosql-fmt/testfiles/dst/select/order_by.sql
crates/uroborosql-fmt/testfiles/src/2way_sql/comment.sql
crates/uroborosql-fmt/testfiles/src/select/order_by.sql

resolve #63 
- `order_by`句でセパレータと式の間に現れるコメントに対応
- 2WaySQLの分岐処理に使われるコメントの場合は行頭にフォーマットされ出力されるよう変更
simple comment:
```sql
-- フォーマット前
select * from foo f
order by
t.bar1
,   /* after comma */
t.bar2
,   t.bar3
-- フォーマット後
select
*
from
foo	f
order by
t.bar1
,	/* after comma */
t.bar2
,	t.bar3
```
2WaySQL:
```sql
-- フォーマット前
select * from foo f
order by
/*IF true*/
f.bar1
,/*END*/
f.bar2
,   f.bar3
-- フォーマット後
select
*
from
foo	f
order by
/*IF true*/
f.bar1
,	
/*END*/
f.bar2
,	f.bar3
```

Fix swapping positions of comma and comment

---

crates/uroborosql-fmt/src/lib.rs
crates/uroborosql-fmt/src/validate.rs
crates/uroborosql-fmt/testfiles/dst/2way_sql/align.sql
crates/uroborosql-fmt/testfiles/src/2way_sql/align.sql

2WaySQLで条件分岐をまたぐ縦ぞろえが崩れる問題（#86）を部分的に修正
- 2WaySQLモードでフォーマットされる条件を変更しました
- 変更前: フォーマット前テキストに`/*IF*/`を含む 場合
- 変更後: フォーマット前テキストに`/*IF*/`を含み、かつ **SQLの構文として不正** な場合
- これにより、通常のSQLとしてパースできる2WaySQLについては縦ぞろえの問題が解消されます
- **通常のSQLとして不正な構文を含む2WaySQLの場合は**、依然として同様の問題が発生し得ます
フォーマット前：
```sql
select
'' as a
/*IF true*/
,'b' as b
/*ELSE*/
,'ccccccccccccccc' as c
/*END*/
;
```
フォーマット後：
```sql
select
''					as	a
/*IF true*/
,	'b'					as	b
/*ELSE*/
,	'ccccccccccccccc'	as	c
/*END*/
;
```

Fix the vertical alignment of 2WaySQL

---

crates/uroborosql-fmt/src/cst/body/insert.rs
crates/uroborosql-fmt/src/visitor/statement/insert.rs
crates/uroborosql-fmt/testfiles/dst/insert/insert_select.sql
crates/uroborosql-fmt/testfiles/src/insert/insert_select.sql

#88 
- insert文の末尾に現れるコメントのうち一部のパターンに対応しました
- 対応したパターン
- insert 文内の select 文の後に現れるコメント 
- 例： `insert into tbl (id) select id from tbl2 where id = 1 -- comment`
- 未対応のパターン
- values句の後に現れるコメント
- 例： `insert into tbl (id) values (1) -- trailing comment`
- 括弧付きinsert文で、閉じ括弧の後に現れるコメント
- 例： `insert into tbl (id) (select id from tbl2 where id = 1) -- comment`
- on conflict句の後に現れるコメント
- 例1： `insert into tbl (did, dname) values (1, 'n') on conflict (did) do nothing -- comment`
- 例2： `insert into tbl (did, name) values (1, 'n') on conflict (did) do update set dname = excluded.dname where did != 10 -- comment`

Handle comments after select_statement at the end of insert_statement

---

crates/uroborosql-fmt/src/visitor/clause/join.rs
crates/uroborosql-fmt/testfiles/dst/select/join.sql
crates/uroborosql-fmt/testfiles/src/select/join.sql

Fix #54 
JOINキーワードの後に現れるコメントをサポートしました
フォーマット前：
```sql
select
*
from
t1
inner join -- after keyword
-- another comment 
t2
on t1.num = t2.num
```
フォーマット後：
```sql
select
*
from
t1
inner join
-- after keyword
-- another comment 
t2
on
t1.num	=	t2.num
;
```

Support comments after join keyword

---

crates/uroborosql-fmt/src/visitor/clause/with.rs
crates/uroborosql-fmt/testfiles/dst/select/with.sql
crates/uroborosql-fmt/testfiles/src/select/with.sql

Fix #91 
`with`句の`recursive`キーワードの後にブロックコメントがあってもフォーマットされるようになりました
```sql
with recursive /* _SQL_ID_ */
t	as	(
select
1
)
select
1
;
```

Handle block comments after recursive keyword

---

crates/uroborosql-fmt/src/cst/expr/column_list.rs
crates/uroborosql-fmt/src/visitor/expr/column_list.rs
crates/uroborosql-fmt/testfiles/dst/comment/col_list_comment.sql
crates/uroborosql-fmt/testfiles/src/comment/col_list_comment.sql

Fix #56 
- `IN` 式の開き括弧の後のコメントをサポートしました
```sql
select
*
from
tbl	t
where
t.id	in	(
-- after opening paren
-- another comment
/*firstId*/0
,	/*secondId*/1
)
;
```

support comments after opening parenthesis in `IN` expression

---

crates/uroborosql-fmt/src/visitor/clause/set.rs
crates/uroborosql-fmt/testfiles/dst/update/update.sql
crates/uroborosql-fmt/testfiles/src/update/update.sql

Close #59 
`SET` キーワードの後のコメントをサポートしました
フォーマット前：
```sql
update
T	t
set -- after set keyword
-- another comment
c	=	c	+	1
where
id	=	1
;
```
フォーマット後：
```sql
update
t	t
set
-- after set keyword
-- another comment
c	=	c	+	1
where
id	=	1
;
```

Support comments after `SET` keyword

---

crates/uroborosql-fmt/src/visitor/statement/insert.rs
crates/uroborosql-fmt/testfiles/dst/insert/insert_select.sql
crates/uroborosql-fmt/testfiles/src/insert/insert_select.sql

Fix #100 
insert文内でselect文前のコメントに対応しました
```sql
insert
into
tbl
(
id
)
-- comments
-- before select
select
id	as	id
from
tbl2
where
id	=	1
;
```

Support comments before select_statement in insert_statement

---

.github/workflows/CI.yml

mac(intel版)でvscode拡張によるSQLフォーマットできない不具合が発生しており、その対応です。
[x86_64向けのBuildジョブ](https://github.com/future-architect/uroborosql-fmt/actions/runs/10823817092/job/30029981935) で `uroborosql-fmt-napi.darwin-arm64.node` が作成されることが原因のようです。
https://github.com/actions/runner-images/issues/9741#issuecomment-2312004709 を参考に、mac(intel版)については `macos-latest-large` のイメージを使用するよう変更しました。
@ota-meshi

fix: macos runner image

---

crates/uroborosql-fmt/testfiles/dst/select/order_by.sql
crates/uroborosql-fmt/testfiles/dst/select/unary.sql
crates/uroborosql-fmt/testfiles/src/select/order_by.sql
crates/uroborosql-fmt/testfiles/src/select/unary.sql

テストケースのうち、不正なSQLを修正しました
1. 複数文から構成されるが、各文の末尾にセミコロンがないもの にセミコロンを付加
- #81 と #63 のテストケース追加時にセミコロンをつけるのを忘れました
- 該当箇所：
- #81: https://github.com/future-architect/uroborosql-fmt/commit/c79404830f219d2577a8e7237da56ebfb13db434#diff-2604424602feeb7005d7d04c5cb2977a6e15d707f7edc2b6757a1390b1b5da65
- #63: https://github.com/future-architect/uroborosql-fmt/commit/97b145fd1076312f85dc279550dce0b96bf65d49#diff-2b59a004d7ffc3852690be046a9d67c9c5e613e34a55e9ec51d44952afae6d92
1. 絶対値演算子 `@` と `-` を空白なしで組み合わせるケースを削除
- `@-` が一つの演算子として扱われるため無効

Fix invalid testcases

---

crates/uroborosql-fmt/src/cst.rs
crates/uroborosql-fmt/src/cst/clause.rs
crates/uroborosql-fmt/src/new_visitor.rs
crates/uroborosql-fmt/src/new_visitor/clause/select.rs
crates/uroborosql-fmt/src/new_visitor/clause/with.rs
crates/uroborosql-fmt/src/new_visitor/expr/subquery.rs
crates/uroborosql-fmt/src/new_visitor/statement/insert.rs
crates/uroborosql-fmt/src/new_visitor/statement/select.rs

以下のケースをサポートしました
```sql
select
```
```sql
select;
```
```sql
select;
select;
```

body なし select をサポート

---

crates/uroborosql-fmt/src/lib.rs
crates/uroborosql-fmt/src/new_visitor.rs
crates/uroborosql-fmt/src/new_visitor/clause/select.rs
crates/uroborosql-fmt/test_normal_cases/dst/009_select_columnref_simple_ident.sql
crates/uroborosql-fmt/test_normal_cases/dst/011_multiple_target_element.sql
crates/uroborosql-fmt/test_normal_cases/dst/012_trailing_comment.sql
crates/uroborosql-fmt/test_normal_cases/dst/013_complement_alias.sql
crates/uroborosql-fmt/test_normal_cases/src/013_complement_alias.sql

カラム参照に対しas句補完機能を実装
PostgreSQLの文法でカラム参照（`columnref`）とされているものに対してのみ補完をする（定数 `AexprConst` 等には補完をしない）
関連： #122

カラムのas句補完機能を実装

---

crates/uroborosql-fmt/src/new_visitor.rs
crates/uroborosql-fmt/src/new_visitor/clause/select.rs
crates/uroborosql-fmt/test_normal_cases/dst/015_sql_id_and_comment.sql
crates/uroborosql-fmt/test_normal_cases/dst/016_bind_param_target_list.sql
crates/uroborosql-fmt/test_normal_cases/src/015_sql_id_and_comment.sql
crates/uroborosql-fmt/test_normal_cases/src/016_bind_param_target_list.sql

- カラムリスト部分のバインドパラメータ
- SQL_ID
- select キーワード後コメント
に対応しました
```sql
select /* _SQL_ID_ */
/*x*/'x'	as	x
,	/*y*/'y'	as	y
;
select
/* comment */
-- comment
a	as	a
;
```

カラムリスト部分のバインドパラメータ・SQL_ID・select キーワード後コメントに対応

---

crates/uroborosql-fmt/tests/README.md
crates/uroborosql-fmt/tests/pgcst_coverage.rs
crates/uroborosql-fmt/tests/pgcst_normal_cases.rs
crates/uroborosql-fmt/tests/pgcst_util.rs
crates/uroborosql-fmt/tests/test_all.rs

カバレッジレポートで Unsupported なケースの理由を出力するオプションを追加
```
cargo test -- --exact test_with_coverage
```
失敗ケースを出力したい場合は 該当のテストにおけるConfigを書き換えて実行します：
```rs
// pgcst_coverage.rs
#[test]
fn test_with_coverage() {
let results = run_test_suite();
// before(default):
// let config = TestReportConfig::default();
// after:
let mut config = TestReportConfig::default();
config.show_failed_cases = true; // 失敗したケースを表示
config.show_error_annotations = true; // アノテーションを表示
print_coverage_report(&results, &config);
}
```
例：

Coverage report のテスト失敗時出力を改善

---

crates/uroborosql-fmt/src/cst/expr/unary.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr.rs
crates/uroborosql-fmt/test_normal_cases/dst/019_unary_expr.sql
crates/uroborosql-fmt/test_normal_cases/src/019_unary_expr.sql
crates/uroborosql-fmt/testfiles/dst/select/unary.sql

式のうち、単項の演算子をサポートしました
PostgreSQLの絶対値演算子(`@`)について、`@-5` のように他の演算子と並べて記述すると `@-` という一つの演算子と認識される挙動がありますが、現行フォーマッタのテストケースではこの点を考慮しないフォーマットをしていたため挙動を変更しました。
commit: https://github.com/future-architect/uroborosql-fmt/pull/131/commits/baae3244b917eaa4833732c68a7857ff42d71312
パーサ移行によって解消される問題としてIssueに起こしました：https://github.com/future-architect/uroborosql-fmt/issues/132

単項演算子をサポート

---

crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/type_cast.rs
crates/uroborosql-fmt/test_normal_cases/dst/034_null_type_cast.sql
crates/uroborosql-fmt/test_normal_cases/src/034_null_type_cast.sql

`::` によるタイプキャストの構文に対応しました
型名にあたる `Typename` ノードは複雑な表現を持ちますが、現在はuroboroSQL-fmt が対応しているシンプルな型名のみを考慮しています。
```sql
'123'::integer
42.5::text
null::text
```
```sql
-- 配列型へのキャスト
expression::integer[]
-- 特定の長さを持つ文字列型へのキャスト
expression::varchar(10)
-- 複数の型キャストを連鎖
'123'::text::varchar(10)
-- 集合型へのキャスト
expression::SETOF text
```

Typecast の構文に対応

---

crates/uroborosql-fmt/src/cst/clause.rs
crates/uroborosql-fmt/src/new_visitor/clause/select.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/in_expr.rs
crates/uroborosql-fmt/test_normal_cases/dst/035_all_distinct.sql
crates/uroborosql-fmt/test_normal_cases/src/035_all_distinct.sql

`select` キーワード後の `all`, `distinct` キーワードおよび `distinct` 句に対応しました
```sql
-- all keyword
select
all
itemid		as	itemid
,	itemname	as	itemname
;
-- distinct keyword
select
distinct
itemid		as	itemid
,	itemname	as	itemname
;
-- distinct clause
select
distinct on
(
quantity
,	itemname
,	area
)
itemid		as	itemid
,	itemname	as	itemname
;
```

all, distinct に対応

---

crates/uroborosql-fmt/src/cst/expr/unary.rs
crates/uroborosql-fmt/testfiles/dst/select/unary.sql
crates/uroborosql-fmt/testfiles/src/select/unary.sql

closes #106 
単項演算がある場合の縦ぞろえがずれている問題を修正しました
input
```sql
select
-1 as c1
,   1 as c2
```
result (before fix)
```sql
select
-1	as	c1
,	1		as	c2
```
result (after fix)
```sql
select
-1	as	c1
,	1	as	c2
```

Fix negative number alignment

---

crates/uroborosql-fmt/src/new_visitor/clause/select.rs
crates/uroborosql-fmt/src/new_visitor/clause/where_clause.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/arithmetic.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/between.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/comparison.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/like.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/logical.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/unary.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/case_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/func_expr/func_application.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/func_expr/func_expr_common_subexpr.rs
crates/uroborosql-fmt/test_normal_cases/dst/037_between.sql
crates/uroborosql-fmt/test_normal_cases/src/037_between.sql

BETWEEN に対応しました
```sql
select
std.grade	as	grade
from
student	std
where
grade	between		/*start1*/60	and	/*end1*/100	-- between
and	grade	not between	/*start2*/70	and	/*end2*/80	-- not between
;
```
PostgreSQL の構文における `b_expr` は、特定の場所で shift/reduce の競合を避けるために利用される式の構文です。
例えば、 BETWEEN 述語は `a_expr BETWEEN b_expr AND a_expr` のように定義され、BETWEEN における`AND` が論理演算における `AND` と競合するのを防いでいます。
以上のような構文解析の事情で `a_expr` と `b_expr` は別々のノードになっていますが、構造としては `b_expr` が  `a_expr` のサブセットになっているため、 visitor を共有できます。
そのため、これまで 利用していた `visit_a_expr` を `visit_a_expr_or_b_expr` として、visitor を共有する実装を採用しました。

BETWEEN 述語に対応

---

crates/uroborosql-fmt/src/new_visitor/statement/select.rs
crates/uroborosql-fmt/test_normal_cases/dst/038_set_operations.sql
crates/uroborosql-fmt/test_normal_cases/src/038_set_operations.sql

SQLにおける代表的な集合演算 （`UNION`, `INTERSECT`, `EXCEPT`）に対応しました
```sql
-- union
select
a	as	a
from
b
union
select
c	as	c
from
b
;
-- intersect
select
a	as	a
from
b
intersect
select
c	as	c
from
b
;
-- except
select
a	as	a
from
b
except
select
c	as	c
from
b
;
```

集合演算（union, intersect, except) に対応

---

crates/uroborosql-fmt/src/new_visitor/clause/from.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/select_with_parens.rs
crates/uroborosql-fmt/src/new_visitor/statement/select.rs
crates/uroborosql-fmt/test_normal_cases/dst/039_subquery_expression.sql
crates/uroborosql-fmt/test_normal_cases/dst/040_subquery_expression_comments.sql
crates/uroborosql-fmt/test_normal_cases/dst/041_nested_select_subquery.sql
crates/uroborosql-fmt/test_normal_cases/dst/042_nested_select_subquery_comments.sql
crates/uroborosql-fmt/test_normal_cases/dst/043_subquery_as_table.sql
crates/uroborosql-fmt/test_normal_cases/dst/044_subquery_as_table_aliased.sql
crates/uroborosql-fmt/test_normal_cases/src/039_subquery_expression.sql
crates/uroborosql-fmt/test_normal_cases/src/040_subquery_expression_comments.sql
crates/uroborosql-fmt/test_normal_cases/src/041_nested_select_subquery.sql
crates/uroborosql-fmt/test_normal_cases/src/042_nested_select_subquery_comments.sql
crates/uroborosql-fmt/test_normal_cases/src/043_subquery_as_table.sql
crates/uroborosql-fmt/test_normal_cases/src/044_subquery_as_table_aliased.sql

select サブクエリに対応しました
- 括弧がネストする場合や、テーブル参照におけるサブクエリにも対応しています。 
- EXISTS クエリおよび IN サブクエリには未対応です。
```sql
select
(
-- comment before statement
select
a	as	a
from
b
-- comment after statement
)
;
```
```sql
select
*
from
(
select
*
from
table1
)	subquery
;
```

select サブクエリに対応

---

crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/exists_subquery.rs
crates/uroborosql-fmt/test_normal_cases/dst/046_exists_subquery.sql
crates/uroborosql-fmt/test_normal_cases/src/046_exists_subquery.sql
crates/uroborosql-fmt/testfiles/dst/select/exists_subquery.sql
crates/uroborosql-fmt/testfiles/src/select/exists_subquery.sql

EXISTS サブクエリに対応しました。
```sql
select
*
from
tbl1
where
exists(
select
col1	as	col1
from
tbl2
where
col1	=	'foo'
)
and	test	=	test
;
```

EXISTS サブクエリに対応

---

crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/all_some_any_subquery.rs
crates/uroborosql-fmt/test_normal_cases/dst/047_all_some_any_subquery.sql
crates/uroborosql-fmt/test_normal_cases/src/047_all_some_any_subquery.sql

ALL, SOME, ANY が現れる式のうちサブクエリに対応しました
```sql
select
*
from
tbl1
where
col1						!=	all	(
select
col1	as	col1
from
tbl2
where
col1	is	not	null
)
and	longlonglonglonglonglong	=		test
;
```
uroboroSQL-fmt のフォーマット機能に合わせた最低限の実装のため、以下は対応していません
- 演算子が `NOT LIKE` や `OPERATOR(any_operator)` のように、複数のノードから成る場合
- 演算子部分のテキストがそのまま使用されます。
- 子ノードまでハンドリングせず、親ノードから得たテキストをそのまま使っているためです。
- サブクエリが来ないパターンの式は未対応です #105 
カバレッジテストで NOT キーワードの `convert_case` が適用されない問題が発生しますが、次の PR で修正します。

ALL, SOME, ANY サブクエリに対応

---

Cargo.lock
crates/uroborosql-fmt/src/new_visitor/clause.rs
crates/uroborosql-fmt/src/new_visitor/clause/sort.rs
crates/uroborosql-fmt/src/new_visitor/statement/select.rs
crates/uroborosql-fmt/test_normal_cases/dst/049_order_by.sql
crates/uroborosql-fmt/test_normal_cases/src/049_order_by.sql

`sort_clause` の処理を実装し、 order by を含むSQLがフォーマットできるようになりました。
```sql
select
col	as	col
from
tab
order by
col			asc					-- 昇順
,	long_col	desc nulls first	-- 降順
,	null_col	nulls first			-- NULL先
;
```

sort 句（order by 句） に対応

---

crates/uroborosql-fmt/src/two_way_sql/tree.rs
crates/uroborosql-fmt/src/visitor.rs

Clippy の新ルール追加により CI が落ちていたので直しました
2025-04-03 の Clippy リリースで追加されたルールでした
- [`doc_overindented_list_items`](https://github.com/rust-lang/rust-clippy/blob/cf9cffa114ce5a780aa8283096bf85c51be7a4f5/CHANGELOG.md?plain=1#L20)
- doc: https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items
- [`double_ended_iterator_last`](https://github.com/rust-lang/rust-clippy/blob/cf9cffa114ce5a780aa8283096bf85c51be7a4f5/CHANGELOG.md?plain=1#L25)
- doc: https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last

clippy を適用

---

crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/aexpr_const.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/func_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/func_expr/func_application.rs
crates/uroborosql-fmt/src/new_visitor/statement/select.rs

postgresql-cst-parser の挙動に沿ったコメントになるよう修正しました
対象としている変更：
- [postgresql-cst-parser: Remove: opt_select_limit, opt_sort_clause #17](https://github.com/future-architect/postgresql-cst-parser/pull/17)
- [postgresql-cst-parser: Remove select_limit node #18](https://github.com/future-architect/postgresql-cst-parser/pull/18)

postgresql-cst-parser のアップデートに伴うコメント修正

---

crates/uroborosql-fmt/src/new_visitor/clause.rs
crates/uroborosql-fmt/test_normal_cases/dst/076_lhs_trailing_comment.sql
crates/uroborosql-fmt/test_normal_cases/src/076_lhs_trailing_comment.sql

エイリアスの AS キーワード直前のコメントに対応しました
```sql
select
t.id	-- コメント1
as	id
;
```

AS 直前のコメントに対応

---

Cargo.lock
crates/uroborosql-fmt/src/lib.rs
crates/uroborosql-fmt/src/new_visitor/clause/sort.rs
crates/uroborosql-fmt/src/pg_validate.rs
crates/uroborosql-fmt/src/two_way_sql.rs
crates/uroborosql-fmt/test_normal_cases/dst/085_2way_mode_begin.sql
crates/uroborosql-fmt/test_normal_cases/dst/086_2way_mode_if.sql
crates/uroborosql-fmt/test_normal_cases/dst/087_2way_mode_comment.sql
crates/uroborosql-fmt/test_normal_cases/src/085_2way_mode_begin.sql
crates/uroborosql-fmt/test_normal_cases/src/086_2way_mode_if.sql
crates/uroborosql-fmt/test_normal_cases/src/087_2way_mode_comment.sql

2way sql mode （分割・マージ機構）でのフォーマットに対応しました。
- パーサでパース出来る場合（エラー回復を含む）はそのままフォーマットされます。
- パースに失敗して、かつ `/*IF ...*/` がある場合にこのモードでフォーマットされます。
- パースに失敗、かつ `/*IF ...*/` が無い（分割の必要性がない）場合はパースエラーとして返されます。
フォーマット結果を検証する `pg_validate_format_result` の実装を lexer ベースのものに変更しました。
理由は以下の3点です。
- もともとの `validate_format_result` でも、木の構造ではなくトークンの並びを比較し検証している
- tree-sitter と違い、 postgresql-cst-parser では lexer にアクセスできる
- postgresql-cst-parser では、SQLの分割・マージが必要なSQLはパースエラーとなるため比較できなくなる（lexer なら問題なし）

2way mode でのフォーマットに対応

---

crates/uroborosql-fmt/src/new_visitor/clause/where_or_current.rs
crates/uroborosql-fmt/test_normal_cases/dst/096_where_or_current_comments.sql
crates/uroborosql-fmt/test_normal_cases/src/096_where_or_current_comments.sql

`where_or_current_clause` におけるキーワード後コメントに対応しました
```sql
update
users
set
status	=	'inactive'
where
/* where clause */
-- current status
status	=	'active'
;
```

where_or_current_clause のキーワード後コメントに対応

---

crates/uroborosql-fmt/src/cst.rs
crates/uroborosql-fmt/src/cst/body/separated_lines.rs
crates/uroborosql-fmt/src/cst/expr/column_list.rs
crates/uroborosql-fmt/src/cst/expr/function.rs
crates/uroborosql-fmt/src/cst/expr_list.rs
crates/uroborosql-fmt/src/lib.rs
crates/uroborosql-fmt/src/new_visitor/clause/select.rs
crates/uroborosql-fmt/src/new_visitor/clause/values.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/a_expr/in_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/func_expr.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/func_expr/func_expr_common_subexpr/trim_function.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/c_expr/implicit_row.rs
crates/uroborosql-fmt/src/new_visitor/pg_expr/expr_list.rs
crates/uroborosql-fmt/src/pg_validate.rs
crates/uroborosql-fmt/src/util.rs
crates/uroborosql-fmt/src/validate.rs
crates/uroborosql-fmt/test_normal_cases/dst/103_partition_by_comments.sql
crates/uroborosql-fmt/test_normal_cases/dst/104_over_trailing_comment.sql
crates/uroborosql-fmt/test_normal_cases/src/103_partition_by_comments.sql
crates/uroborosql-fmt/test_normal_cases/src/104_over_trailing_comment.sql
crates/uroborosql-fmt/tests/pgcst_coverage.rs
crates/uroborosql-fmt/tests/pgcst_normal_cases.rs

`partition by` 句のカラム部分に行末コメントとバインド変数以外のコメントを書けるようにしました
```sql
select
count(*) over(
partition by
a
/*IF 1 = 1*/
,	b
/*END*/
)	as	c
from
t
;
```
これまで `visit_expr_list` の返り値は `Vec<AlignedExpr>` としており、`expr_list` で表される箇所では行末コメントとバインド変数以外のコメントは想定しない作りとなっていました。
しかし、新パーサで `expr_list` として扱われる箇所のうち、フォーマッタ内部で `SeparatedLines` として表現されている箇所については、式の次行以降にコメントを書けることが想定されています。
よって、`visit_expr_list` の返り値を、内部にコメントを保持する `ExprList` として表現するよう変更しました。利用側では visit_expr_list を呼び出した後に、必要な各構造体（`SeparatedLines`, `ColumnList`, `FunctionCallArgs`）へ変換します。 
よって、 `SeparatedLines` で表現されている `partition by` 句のカラムリスト部分に新しくコメントが書けるようになりました。
`ColumnList` や `FunctionCallArgs` については `SeparatedLines` のようなコメント（行末コメントやバインド変数以外のコメント）は想定されていないため、もしそれにあたるコメントがある場合は変換時にエラーとなるようにしています。

partition by 句のコメントに対応

---

crates/uroborosql-fmt/src/visitor/clause/offset.rs
crates/uroborosql-fmt/testfiles/dst/select/limit_offset.sql
crates/uroborosql-fmt/testfiles/src/select/limit_offset.sql

offset keyword 直後のバインドパラメータに対応しました。
```sql
select
*
from
t
offset	/*bind*/5
;
```

offset keyword 直後のバインドパラメータに対応

---

.cargo/config.toml
Cargo.lock
README.md
crates/uroborosql-fmt-cli/Cargo.toml
crates/uroborosql-fmt-cli/README.md
crates/uroborosql-fmt-cli/src/cli.rs
crates/uroborosql-fmt-cli/src/main.rs
crates/uroborosql-fmt-cli/tests/cli.rs
crates/uroborosql-fmt-cli/tests/cli_ext.rs

CLI 版に機能を追加しました。
主な変更点は以下です。
- 標準入出力対応
- 終了コード出し分け
- config file のパス指定
具体的な仕様は [CLI版の README](https://github.com/future-architect/uroborosql-fmt/blob/feat/cli-improvement/crates/uroborosql-fmt-cli/README.md) に記載しました。

CLI版の改善・機能追加

---

crates/uroborosql-fmt/src/visitor/expr/c_expr/columnref.rs
crates/uroborosql-fmt/test_normal_cases/dst/106_bind_param_columnref.sql
crates/uroborosql-fmt/test_normal_cases/src/106_bind_param_columnref.sql

Close #207
テーブル参照で置換文字列を使用するとコメントのcaseが変換されてしまうバグを修正しました。
原因は`visitor/expr/c_expr/columnref.rs`において、`indirection`をそのままテキストに変換して大文字小文字変換を行っていたため、以下のように`indirection`の子に`C_COMMENT`が含まれていた場合にコメントも同時に大文字小文字変換してしまっていたためでした。
```
indirection [(5, 4)-(5, 31)]
indirection_el [(5, 4)-(5, 31)]
Dot [(5, 4)-(5, 5)]
C_COMMENT [(5, 5)-(5, 27)]
attr_name [(5, 27)-(5, 31)]
ColLabel [(5, 27)-(5, 31)]
IDENT [(5, 27)-(5, 31)]
```
before:
```sql
select /* _SQL_ID_ */
*
from
tbl
where
tbl./*$targetColumnName1*/col1	
is	null
and  		schema1. tbl./*$targetColumnName2*/col2 is not null
and /*$targetColumnName1*/col1 + tbl.   /*$targetColumnName2*/col2 = 10
;
```
after:
```sql
select /* _SQL_ID_ */
*
from
tbl
where
tbl./*$targetColumnName1*/col1									is	null
and	schema1.tbl./*$targetColumnName2*/col2							is	not …
```

Preserve case of comments in WHERE clauses

---

crates/uroborosql-fmt/src/visitor/expr/a_expr/like.rs
crates/uroborosql-fmt/test_normal_cases/dst/108_ilike.sql
crates/uroborosql-fmt/test_normal_cases/src/108_ilike.sql

Close #211
before
```sql
SELECT * FROM users WHERE name ILIKE 'test%';
```
after
```sql
select
*
from
users
where
name	ILIKE	'test%'
;
```

Support ILIKE
